#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : liburing
Version  : 2.2
Release  : 4
URL      : https://github.com/axboe/liburing/archive/liburing-2.2/liburing-2.2.tar.gz
Source0  : https://github.com/axboe/liburing/archive/liburing-2.2/liburing-2.2.tar.gz
Summary  : Linux-native io_uring I/O access library
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1 MIT
Requires: liburing-lib = %{version}-%{release}
Requires: liburing-license = %{version}-%{release}
Requires: liburing-man = %{version}-%{release}
Patch1: 0001-Warn-for-unknown-configure-options.patch

%description
Provides native async IO for the Linux kernel, in a fast and efficient
manner, for both buffered and O_DIRECT.

%package dev
Summary: dev components for the liburing package.
Group: Development
Requires: liburing-lib = %{version}-%{release}
Provides: liburing-devel = %{version}-%{release}
Requires: liburing = %{version}-%{release}

%description dev
dev components for the liburing package.


%package lib
Summary: lib components for the liburing package.
Group: Libraries
Requires: liburing-license = %{version}-%{release}

%description lib
lib components for the liburing package.


%package license
Summary: license components for the liburing package.
Group: Default

%description license
license components for the liburing package.


%package man
Summary: man components for the liburing package.
Group: Default

%description man
man components for the liburing package.


%prep
%setup -q -n liburing-liburing-2.2
cd %{_builddir}/liburing-liburing-2.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656351564
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static --libdevdir=/usr/lib64
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1656351564
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/liburing
cp %{_builddir}/liburing-liburing-2.2/COPYING %{buildroot}/usr/share/package-licenses/liburing/3704f4680301a60004b20f94e0b5b8c7ff1484a9
cp %{_builddir}/liburing-liburing-2.2/COPYING.GPL %{buildroot}/usr/share/package-licenses/liburing/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/liburing-liburing-2.2/debian/copyright %{buildroot}/usr/share/package-licenses/liburing/804982ee6d3905270c9dd405d4ee811ffc8ab902
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/liburing.h
/usr/include/liburing/barrier.h
/usr/include/liburing/compat.h
/usr/include/liburing/io_uring.h
/usr/lib64/liburing.so
/usr/lib64/pkgconfig/liburing.pc
/usr/share/man/man2/io_uring_enter.2
/usr/share/man/man2/io_uring_register.2
/usr/share/man/man2/io_uring_setup.2
/usr/share/man/man3/io_uring_buf_ring_add.3
/usr/share/man/man3/io_uring_buf_ring_advance.3
/usr/share/man/man3/io_uring_buf_ring_cq_advance.3
/usr/share/man/man3/io_uring_buf_ring_init.3
/usr/share/man/man3/io_uring_buf_ring_mask.3
/usr/share/man/man3/io_uring_cq_advance.3
/usr/share/man/man3/io_uring_cq_ready.3
/usr/share/man/man3/io_uring_cqe_get_data.3
/usr/share/man/man3/io_uring_cqe_get_data64.3
/usr/share/man/man3/io_uring_cqe_seen.3
/usr/share/man/man3/io_uring_free_probe.3
/usr/share/man/man3/io_uring_get_probe.3
/usr/share/man/man3/io_uring_get_sqe.3
/usr/share/man/man3/io_uring_opcode_supported.3
/usr/share/man/man3/io_uring_peek_cqe.3
/usr/share/man/man3/io_uring_prep_accept.3
/usr/share/man/man3/io_uring_prep_accept_direct.3
/usr/share/man/man3/io_uring_prep_cancel.3
/usr/share/man/man3/io_uring_prep_cancel64.3
/usr/share/man/man3/io_uring_prep_close.3
/usr/share/man/man3/io_uring_prep_close_direct.3
/usr/share/man/man3/io_uring_prep_connect.3
/usr/share/man/man3/io_uring_prep_fadvise.3
/usr/share/man/man3/io_uring_prep_fallocate.3
/usr/share/man/man3/io_uring_prep_files_update.3
/usr/share/man/man3/io_uring_prep_fsync.3
/usr/share/man/man3/io_uring_prep_link.3
/usr/share/man/man3/io_uring_prep_linkat.3
/usr/share/man/man3/io_uring_prep_madvise.3
/usr/share/man/man3/io_uring_prep_mkdir.3
/usr/share/man/man3/io_uring_prep_mkdirat.3
/usr/share/man/man3/io_uring_prep_msg_ring.3
/usr/share/man/man3/io_uring_prep_multishot_accept.3
/usr/share/man/man3/io_uring_prep_multishot_accept_direct.3
/usr/share/man/man3/io_uring_prep_openat.3
/usr/share/man/man3/io_uring_prep_openat2.3
/usr/share/man/man3/io_uring_prep_openat2_direct.3
/usr/share/man/man3/io_uring_prep_openat_direct.3
/usr/share/man/man3/io_uring_prep_poll_add.3
/usr/share/man/man3/io_uring_prep_poll_multishot.3
/usr/share/man/man3/io_uring_prep_poll_remove.3
/usr/share/man/man3/io_uring_prep_poll_update.3
/usr/share/man/man3/io_uring_prep_provide_buffers.3
/usr/share/man/man3/io_uring_prep_read.3
/usr/share/man/man3/io_uring_prep_read_fixed.3
/usr/share/man/man3/io_uring_prep_readv.3
/usr/share/man/man3/io_uring_prep_readv2.3
/usr/share/man/man3/io_uring_prep_recv.3
/usr/share/man/man3/io_uring_prep_recvmsg.3
/usr/share/man/man3/io_uring_prep_remove_buffers.3
/usr/share/man/man3/io_uring_prep_rename.3
/usr/share/man/man3/io_uring_prep_renameat.3
/usr/share/man/man3/io_uring_prep_send.3
/usr/share/man/man3/io_uring_prep_sendmsg.3
/usr/share/man/man3/io_uring_prep_shutdown.3
/usr/share/man/man3/io_uring_prep_socket.3
/usr/share/man/man3/io_uring_prep_socket_direct.3
/usr/share/man/man3/io_uring_prep_splice.3
/usr/share/man/man3/io_uring_prep_statx.3
/usr/share/man/man3/io_uring_prep_symlink.3
/usr/share/man/man3/io_uring_prep_symlinkat.3
/usr/share/man/man3/io_uring_prep_sync_file_range.3
/usr/share/man/man3/io_uring_prep_tee.3
/usr/share/man/man3/io_uring_prep_timeout.3
/usr/share/man/man3/io_uring_prep_timeout_remove.3
/usr/share/man/man3/io_uring_prep_timeout_update.3
/usr/share/man/man3/io_uring_prep_unlink.3
/usr/share/man/man3/io_uring_prep_unlinkat.3
/usr/share/man/man3/io_uring_prep_write.3
/usr/share/man/man3/io_uring_prep_write_fixed.3
/usr/share/man/man3/io_uring_prep_writev.3
/usr/share/man/man3/io_uring_prep_writev2.3
/usr/share/man/man3/io_uring_queue_exit.3
/usr/share/man/man3/io_uring_queue_init.3
/usr/share/man/man3/io_uring_queue_init_params.3
/usr/share/man/man3/io_uring_register_buf_ring.3
/usr/share/man/man3/io_uring_register_buffers.3
/usr/share/man/man3/io_uring_register_eventfd.3
/usr/share/man/man3/io_uring_register_eventfd_async.3
/usr/share/man/man3/io_uring_register_files.3
/usr/share/man/man3/io_uring_register_iowq_aff.3
/usr/share/man/man3/io_uring_register_iowq_max_workers.3
/usr/share/man/man3/io_uring_register_ring_fd.3
/usr/share/man/man3/io_uring_sq_ready.3
/usr/share/man/man3/io_uring_sq_space_left.3
/usr/share/man/man3/io_uring_sqe_set_data.3
/usr/share/man/man3/io_uring_sqe_set_data64.3
/usr/share/man/man3/io_uring_sqe_set_flags.3
/usr/share/man/man3/io_uring_sqring_wait.3
/usr/share/man/man3/io_uring_submit.3
/usr/share/man/man3/io_uring_submit_and_wait.3
/usr/share/man/man3/io_uring_submit_and_wait_timeout.3
/usr/share/man/man3/io_uring_unregister_buf_ring.3
/usr/share/man/man3/io_uring_unregister_buffers.3
/usr/share/man/man3/io_uring_unregister_eventfd.3
/usr/share/man/man3/io_uring_unregister_files.3
/usr/share/man/man3/io_uring_unregister_iowq_aff.3
/usr/share/man/man3/io_uring_unregister_ring_fd.3
/usr/share/man/man3/io_uring_wait_cqe.3
/usr/share/man/man3/io_uring_wait_cqe_nr.3
/usr/share/man/man3/io_uring_wait_cqe_timeout.3
/usr/share/man/man3/io_uring_wait_cqes.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/liburing.so.2
/usr/lib64/liburing.so.2.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/liburing/3704f4680301a60004b20f94e0b5b8c7ff1484a9
/usr/share/package-licenses/liburing/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/liburing/804982ee6d3905270c9dd405d4ee811ffc8ab902

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man7/io_uring.7
